# Generated by Django 5.2.8 on 2026-01-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photographer_note',
            field=models.TextField(blank=True, verbose_name='Примечание фотографа'),
        ),
    ]
