# Generated by Django 5.2.8 on 2026-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_photographer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryaccess',
            name='original_role',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Клиент (Выбор фото)'), ('VIEWER', 'Зритель (Только просмотр)')], max_length=20, null=True),
        ),
    ]
