# Generated by Django 5.2.8 on 2026-01-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryaccess_original_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя'),
        ),
    ]
